### ISSUE TITLE
The `kernel` role should configure bootloaders

### ISSUE THREAD

**Issue by crichez** [crichez/crichez.secureboot#27]
## Background

The `kernel` role currently only allows configuring shim as a first stage bootloader, and the kernel stub as the second stage. This is a little limiting, since not everyone can access UEFI boot options over the network or via a serial console.

## Solution

We should support specifying a desired bootloader and configure it accordingly.

## Implementation

The `kernel_bootloader` option can take a string that describes the bootloader to configure:
```yaml
kernel_bootloader:
  type: str
  default: stub
  description: >-
    The name of the bootloader that should be launched by shim after secure boot validation.
  choices:
    - stub
    - grub
    - sd-boot
```

## Alternatives

Restricting the list of bootloaders will help us confine the scope of the change, but it may be advisable to simply ask for an EFI binary path and update UEFI variables accordingly. This is more flexible, but requires the caller to set up a signed UEFI binary on their own, which may not be accessible to most administrators. We could find middle ground and add a "path" choice to the argument above, and a second `kernel_bootloader_path` argument that points to the signed UEFI binary.

It is also worth considering whether this is in the scope of this role. Right now we configure the kernel stub as the second stage bootloader, but maybe removing all bootloader configuration is more sensible, and then we can create a `bootloader` role that does what this PR describes. This removes a lot of functionality from this role, and essentially makes it useless on its own. This would also require a major version change.
